-- MySQL Script generated by MySQL Workbench
-- Mon Nov 22 16:46:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_samson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_samson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_samson` DEFAULT CHARACTER SET utf8 ;
USE `test_samson` ;

-- -----------------------------------------------------
-- Table `test_samson`.`a_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_category` (
  `ид` INT NOT NULL AUTO_INCREMENT,
  `код` INT NOT NULL,
  `название` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`название`),
  INDEX `category_id` () VISIBLE,
  INDEX `category_code` () VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_samson`.`a_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_product` (
  `ид` INT NOT NULL AUTO_INCREMENT,
  `код` INT NOT NULL,
  `категория` VARCHAR(25) NOT NULL,
  `название` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`название`),
  INDEX `product_id` () VISIBLE,
  INDEX `product_code` () VISIBLE,
  INDEX `category_idx` (`категория` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`категория`)
    REFERENCES `test_samson`.`a_category` (`название`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_samson`.`a_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_price` (
  `товар` VARCHAR(25) NOT NULL,
  `тип цены` VARCHAR(50) NOT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  INDEX `product_idx` (`товар` ASC) VISIBLE,
  INDEX `price_type` () VISIBLE,
  INDEX `price` () VISIBLE,
  CONSTRAINT `product`
    FOREIGN KEY (`товар`)
    REFERENCES `test_samson`.`a_product` (`название`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_samson`.`a_property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_property` (
  `товар` VARCHAR(25) NOT NULL,
  `значение свойства` VARCHAR(100) NOT NULL,
  INDEX `product_idx` (`товар` ASC) VISIBLE,
  INDEX `property_value` () VISIBLE,
  CONSTRAINT `product`
    FOREIGN KEY (`товар`)
    REFERENCES `test_samson`.`a_product` (`название`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
